
#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: indy-sdk-react-native
  description: React Native wrapper around Indy SDK Java and Objective-C wrappers.
  default_branch: main
  has_downloads: true
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
